.PHONY: clean All

All:
	@echo "----------Building project:[ write-in-files - Debug ]----------"
	@cd "write-in-files" && "$(MAKE)" -f  "write-in-files.mk"
clean:
	@echo "----------Cleaning project:[ write-in-files - Debug ]----------"
	@cd "write-in-files" && "$(MAKE)" -f  "write-in-files.mk" clean
