.PHONY: clean All

All:
	@echo "----------Building project:[ allocation-dynamic - Debug ]----------"
	@cd "allocation-dynamic" && "$(MAKE)" -f  "allocation-dynamic.mk"
clean:
	@echo "----------Cleaning project:[ allocation-dynamic - Debug ]----------"
	@cd "allocation-dynamic" && "$(MAKE)" -f  "allocation-dynamic.mk" clean
