.PHONY: clean All

All:
	@echo "----------Building project:[ SDL-img - Debug ]----------"
	@cd "SDL-img" && "$(MAKE)" -f  "SDL-img.mk"
clean:
	@echo "----------Cleaning project:[ SDL-img - Debug ]----------"
	@cd "SDL-img" && "$(MAKE)" -f  "SDL-img.mk" clean
